@startuml Auto
class Auto {
  marca : string
  modello : string
  targa : string
  km_percorsi : int
  stato : string

  constructor(marca : string, modello : string, targa : string, km_percorsi : int, stato : string)
  effettua_viaggio(km: int) : void
  incrementa_anno() : void
  verifica_stato() : bool
}
@enduml