```plantuml ContoBancario
@startuml ContoBancario
class ContoBancario {
  + titolare : string
  - saldo : float
  --
  + __init__(titolare: string, saldo_iniziale: float)
  + deposita(importo: float) : void
  + preleva(importo: float) : void
  + mostra_saldo() : float
}
@enduml