classDiagram
    class Camera {
        -int numero
        -str tipo
        -bool disponibile
        +int get_numero()
        +str get_tipo()
        +bool is_disponibile()
        +void set_disponibile(bool stato)
    }
    
    class Prenotazione {
        -str cliente
        -date data_inizio
        -date data_fine
        +str get_cliente()
        +tuple[date, date] get_date()
    }
    
    class Albergo {
        -str nome_albergo
        +str get_nome_albergo()
    }

    Prenotazione "1" --> "1" Camera: si_riferisce_a
    Albergo "1" --> "*" Camera: composto_da
    Albergo "1" --> "*" Prenotazione: ha