classDiagram
    class Camera {
        -int numero
        -str tipo
        -bool disponibile
        +int get_numero()
        +str get_tipo()
        +bool is_disponibile()
        +void set_disponibile(bool stato)
    }
    
    class Prenotazione {
        -Camera camera
        -str cliente
        -date data_inizio
        -date data_fine
        +Camera get_camera()
        +str get_cliente()
        +tuple[date, date] get_date()
    }
    
    class Albergo {
        -str nome_albergo
        -list[Camera] camere
        -list[Prenotazione] prenotazioni
        +str get_nome_albergo()
        +void aggiungi_camera(Camera camera)
        +Prenotazione prenota_camera(int numero, str cliente, date inizio, date fine)
        +list[Camera] get_camere_disponibili()
        +list[Prenotazione] get_prenotazioni()
    }

    Prenotazione "1" --> "1" Camera: si_riferisce_a
    Albergo "1" --> "*" Camera: composto_da
    Albergo "1" --> "*" Prenotazione: ha